application: daycount101
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: daycount.py